package com.phuoctnb.dexauto.payment

data class BankOption(
    val code: String,
    val shortName: String
) {
    val label: String get() = "$shortName - $code"
}

object VietQrBankCatalog {
    // Snapshot collected from VietQR on 2026-07-24. The app never fetches the bank catalog at runtime.
    val banks: List<BankOption> = listOf(
        BankOption(code = "TCB", shortName = "Techcombank"),
        BankOption(code = "COOPBANK", shortName = "COOPBANK"),
        BankOption(code = "ACB", shortName = "ACB"),
        BankOption(code = "KBHN", shortName = "KookminHN"),
        BankOption(code = "IBK", shortName = "IBK"),
        BankOption(code = "VAB", shortName = "VietABank"),
        BankOption(code = "MSB", shortName = "MSB"),
        BankOption(code = "ABB", shortName = "ABBANK"),
        BankOption(code = "LIOBANK", shortName = "LioBank"),
        BankOption(code = "VPB", shortName = "VPBank"),
        BankOption(code = "CBB", shortName = "CBBank"),
        BankOption(code = "KPB", shortName = "KBank"),
        BankOption(code = "WRB", shortName = "Woori"),
        BankOption(code = "HSBC", shortName = "HSBC"),
        BankOption(code = "BNPHCM", shortName = "BNPHCM"),
        BankOption(code = "GPB", shortName = "GPBank"),
        BankOption(code = "PBVN", shortName = "PublicBank"),
        BankOption(code = "CAKE", shortName = "CAKE"),
        BankOption(code = "VTB", shortName = "Vietinbank"),
        BankOption(code = "BVB", shortName = "BaoVietBank"),
        BankOption(code = "HONGLEONG", shortName = "HongLeong"),
        BankOption(code = "KEBHCM", shortName = "KEBHanaHCMBank"),
        BankOption(code = "BNPHN", shortName = "BNPHN"),
        BankOption(code = "VIB", shortName = "VIB"),
        BankOption(code = "VRB", shortName = "VRB"),
        BankOption(code = "OCB", shortName = "OCB"),
        BankOption(code = "BAB", shortName = "BacABank"),
        BankOption(code = "KBHCM", shortName = "KookminHCM"),
        BankOption(code = "DAB", shortName = "DongABank"),
        BankOption(code = "CITIBANK", shortName = "CitibankHN"),
        BankOption(code = "NCB", shortName = "NCB"),
        BankOption(code = "VCAB", shortName = "VietCapitalBank"),
        BankOption(code = "DBS", shortName = "DBSBank"),
        BankOption(code = "NHB", shortName = "Nonghyup"),
        BankOption(code = "VTLMONEY", shortName = "ViettelMoney"),
        BankOption(code = "LPB", shortName = "LPBank"),
        BankOption(code = "STB", shortName = "Sacombank"),
        BankOption(code = "Ubank", shortName = "Ubank"),
        BankOption(code = "SHINHAN", shortName = "ShinhanBank"),
        BankOption(code = "SBC", shortName = "SaigonBank"),
        BankOption(code = "AGR", shortName = "Agribank"),
        BankOption(code = "HDB", shortName = "HDBank"),
        BankOption(code = "PGB", shortName = "PGBank"),
        BankOption(code = "MB", shortName = "MBBank"),
        BankOption(code = "BIDC", shortName = "BIDC"),
        BankOption(code = "SAB", shortName = "SeABank"),
        BankOption(code = "VNPTMONEY", shortName = "VNPTMoney"),
        BankOption(code = "SHB", shortName = "SHB"),
        BankOption(code = "NAB", shortName = "NamABank"),
        BankOption(code = "CUBHCM", shortName = "CathayUnitedBank"),
        BankOption(code = "PVCB", shortName = "PVcomBank"),
        BankOption(code = "VBC", shortName = "VietBank"),
        BankOption(code = "UOB", shortName = "UnitedOverseas"),
        BankOption(code = "TPB", shortName = "TPBank"),
        BankOption(code = "UMEE", shortName = "KienLongBank"),
        BankOption(code = "CIMB", shortName = "CIMB"),
        BankOption(code = "KLB", shortName = "KienLongBank"),
        BankOption(code = "VCB", shortName = "Vietcombank"),
        BankOption(code = "TIMO", shortName = "Timo"),
        BankOption(code = "IVB", shortName = "IndovinaBank"),
        BankOption(code = "SCB", shortName = "SCB"),
        BankOption(code = "BIDV", shortName = "BIDV"),
        BankOption(code = "EIB", shortName = "Eximbank"),
        BankOption(code = "SCVN", shortName = "StandardChartered"),
        BankOption(code = "MBV", shortName = "Oceanbank"),
        BankOption(code = "KEBHN", shortName = "KEBHanaHNBank")
    ).sortedBy(BankOption::shortName)
}
